parameters:
services:
    tactics.object_route_resolver:
        class: Tactics\Bundle\AdminBundle\ObjectRouteResolver\ObjectRouteResolver
        arguments: 
            - @service_container
    tactics.updater_loggable_listener:
        class: Tactics\Bundle\AdminBundle\Listener\UpdaterLoggableListener        
        arguments:                          
            - @service_container
        tags: 
            - { name: doctrine.event_subscriber }
